### PR TITLE
listen a 'connect' event of websocket

### PR DESCRIPTION
**Pull request by wm123450405**
The callback function of router.socket('connect', callback) will be called when a new socket connection connected. By this, you can listen a 'connect' event

### CODE REVIEW

**Comment by franciscop** [comment]
Hi @wm123450405 , thank you so much for the PR. I think something like this was initially implemented but lost. Unfortunately testing websockets it's not so easy as I wish, so things are bound to be broken until a suitable solution is found. Meanwhile `const { socket } = server.router` is not even officially supported.

That said, this PR looks great, so if you sign the CLA I'll merge it ASAP. Thank you so much for contributing! If you find any bug let me know and I'll try to fix it.

**Comment by franciscop** [comment]
@wm123450405 could you please sing the CLA? Otherwise I cannot continue with this Pull Request.

**Comment by wm123450405** [comment]
sorry, I have already signed the CLA

**Comment by franciscop** [comment]
Great, thank you! Please note that `socket` won't be officially released until `1.1`, so I wouldn't recommend using it in production as it will probably change (for instance, to allow for `require('server/router/socket')`.

**Pull request merged**
