### PR TITLE
nunjucks, added to README

### PR DESCRIPTION
**Pull request by coderam**
added Nunjucks

### CODE REVIEW

**Comment by franciscop** [comment]
Hi @coderam, thanks for the PR. Unfortunately the homepage is not the place to document this. From your emails and your past issue comments I see you really like nunjucks, but this documentation would normally be in the documentation for the **options**, on the **engine** section.

**However** this PR is actually *not* showing the power of `express` engines, it is showing how to make an engine manually. So it is more equivalent to showing the default text reply [as explained here](https://github.com/franciscop/server/issues/34#issuecomment-343787590):

```js
server(ctx => `
<!DOCTYPE html>
<html>
  ...
</html>
`);
```

However with the new version, a new engine is a lot easier to do, for this situation you could do it just like this (and it will join the options with the locals correctly):

```js
const engine = {
  nunjucks: (file, options) => require('nunjucks').render(file, options)
};

server({ engine }, ctx => render('index', { any: 'option' }));
```

All of this work is going on on the `plugins` branch, which will become `1.1`. See specifically [this](https://github.com/franciscop/server/blob/plugins/plugins/express/integration.test.js#L51) and [this](https://github.com/franciscop/server/blob/plugins/plugins/express/integration.test.js#L64) tests, one using a legacy engine and the other using ES6 (the difference is the function signature/the argument length).

Feel free to add a PR to the `plugins` branch, `options` page in the `engine` section.

It is still work in progress but I start to be happy with the state of the code and tests, so mostly I just have to document things and clean up the code a bit to kick it off. Cannot say a date (I started working full time in January and time has been tight) but I really want to see 1.1 released. Feel free to try the `1.1.0-alpha.3` *carefully* (it is an alpha) and fill any bug you find.

Note: please keep messages about server.js in the Github issues instead of emailing me, since they will work great as a reference for the future and my inbox is a mess.

**Comment by dannluciano** [comment]
Hi guys, ```ctx.locals``` is valid? Inspecting my ```ctx``` I cannot find ```locals``` object.

**Comment by coderam** [comment]
@franciscop hi,

I tried just about every option for getting nunjucks to work, here are my options dict:

var options = {
    defaultEngine: "nunjucks",
    ext: ".nunjucks",
    nunjucks: (file, options) => require('nunjucks').render(file, options),
    engine: "nunjucks",
}; 

Upgraded to your alpha3 version :)

Here is the view: 
server(options,[
get('/index.html',
        ctx => render('index.nunjucks', 
                                 {  chai: "chai", 
                                    settings: settings,
                                    options: options,
                                    treeternities: treeternities_each
                                 }
                     
        )),
]);

Get the following error, 

ERROR Error: Module "nunjucks" does not provide a view engine.
    at new View (/home/acer/nodespace/node_modules/express/lib/view.js:84:13)
    at Function.render (/home/acer/nodespace/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (/home/acer/nodespace/node_modules/express/lib/response.js:1008:7)
    at Promise (/home/acer/nodespace/node_modules/server/reply/reply.js:139:13)
    at new Promise (<anonymous>)
    at stack.push.ctx (/home/acer/nodespace/node_modules/server/reply/reply.js:136:26)
    at Reply.exec (/home/acer/nodespace/node_modules/server/reply/reply.js:175:11)
    at processReturn (/home/acer/nodespace/node_modules/server/src/join/index.js:11:22)
    at /home/acer/nodespace/node_modules/server/src/join/index.js:43:17
    at <anonymous>

Please re-open, this is pretty important for your new version release and excited about the new engine :)

**Comment by coderam** [comment]
@dannluciano I think in the newer versions of Server.js, the ctx.locals is removed...

**Comment by franciscop** [comment]
@dannluciano hi could you open a separate issue with more info please? `ctx.locals` should be available, otherwise it's a bug.

**Comment by franciscop** [comment]
@coderam the alpha version is still work in progress, let me look into that. This PR is totally unrelated to the specific error, so please feel free to open a separated issue to keep track of things. I'll have a look into that, now that engines are more relevant I might add them as an example/separated test, and I can use nunjucks for that.

**Comment by franciscop** [comment]
@coderam just tried it and the code I put works without a problem in server@1.1.0-alpha.3, [please have a look into this folder](https://github.com/franciscop/server/tree/plugins/examples/nunjucks):

```js
const server = require('server');   // Note: local path in the /examples folder
const { get } = server.router;
const { render } = server.reply;

const engine = {
  nunjucks: (file, options) => require('nunjucks').render(file, options)
};

const chai = 'Chai Name';
server({ engine }, ctx => render('index.nunjucks', { chai }));
```

If you are still facing issues, please open a separated issue :smile:

**Pull request closed without merging**
