### PR TITLE
Ability to provide a custom logger

### PR DESCRIPTION
**Pull request by amercier**
This PR adds a new `instance` option to the `log` plugin.

Please read updated `README.md` included within this PR for details.

- [x] Implementation
- [x] Updated tests
- [x] Updated documentation

### CODE REVIEW

**Comment by franciscop** [comment]
Could you please provide a user-case where this might be useful? I feel this is the wrong level of abstraction, like it should either go up one level to provide a full new logger for userland (only), or down one level for writing the output to a specific place (`report` option).

The issue is `log` is used internally, so if you change the signature things can break in very unpredictable ways.

**Comment by amercier** [comment]
Here's my use case:

> **Note:** all of this would be achievable by creating an instance of my custom logger, and passing it to all middlewares and routes as an argument (using some sort of `Factory` pattern style: `module.export = (log) => function(ctx) { /* ... */ }`. But I would like to leverage server.js's context to pass this. Maybe this is the wrong way of doing this?

### Multiple streams

I want a logger that logs any error/warning to `stderr` and all the rest to `stdout`. This way I can easily do something like: `npm start >out.log 2>errors.log`.

### Pretty output

I want colored logs, this way I can easily spot errors/warning during development.

Example:
image

For instance I have the following error handler:

```js
const router = require('server/router');
const { cyan, yellow, magenta } = require('chalk');

class HttpError extends Error { /* ... */ }

function handleError(ctx) {
  if (error instanceof HttpError) {
    if (error.status < 500) { // 4xx
      ctx.log.notice(`Responding ${yellow(error)} to request ${cyan(`${ctx.method} ${ctx.url}`)}`);
    } else { // 5xx
      ctx.log.warning(`Responding ${magenta(error)} to request ${cyan(`${ctx.method} ${ctx.url}`)}`);
    }
    return replyStatus(error.status).render(`${error.status}.pug`);
  }

  // Not a HTTP error
  ctx.log.error('Uncaught error!', error);
  return renderError(ctx, new HttpError(500));
}

const errorHandlerMiddleware = router.error(handleError);
```

Output:

image

Also, my logger leverages [jest-message-util](https://github.com/facebook/jest/tree/master/packages/jest-message-util) to produce nice error messages:

image

### Same logger for middlewares/routes and server start error (catch block)

Example with my `app.js` (simplified for clarity):
```js
const server = require('server');

const log = new MyCustomLog(...);

const config = {
  log: { instance: log }
};
const middlewares = [ /* ... */ ];
const routes = [ /* ... */ ];

module.exports = server(
  config,
  ...middlewares,
  routes,
  errorHandlerMiddleware,
).then((ctx) => {
  const { port, env } = ctx.options;
  ctx.log.info(`Started server in ${cyan(env)} mode, listening on port ${cyan(port)}`);
}).catch(({ message }) => {
  log.critical(`Could not start server: ${red(message)}`); // <== I can use log 
  process.exit(1);
});
```

### Display time

My custom logger has a `displayTime` option that allow displaying time of logging:

image

I set this option by default to `true` in `production` mode, and false in other modes.

**Comment by vorticalbox** [comment]
You could use Winston then create a wrapper.

```JavaScript
const LOG_DIR    = process.env.LOG_DIR;
const LOG_PREFIX = process.env.LOG_PREFIX;

const fs = require('fs');
const path = require('path');
const winston = require('winston');

fs.existsSync(LOG_DIR) || fs.mkdirSync(LOG_DIR);
fs.existsSync(path.join(LOG_DIR, LOG_PREFIX)) || fs.mkdirSync(path.join(LOG_DIR, LOG_PREFIX));

/**
 * Returns a timestamp
 * @returns {string} current time as string
 */
function tsFormat() {
    return (new Date()).toLocaleTimeString(); 
}

const logger = new (winston.Logger)({
    transports: [
        new (winston.transports.Console)({ 
            colorize: true,
            prettyPrint: true,
            timestamp: tsFormat,
            level: process.env.NODE_ENV === 'production' ? 'info' : 'debug',
        }),
        new (winston.transports.File)({
            colorize: true,
            prettyPrint: true,
            name: 'file#error',
            filename: `${LOG_DIR}/${LOG_PREFIX}/${LOG_PREFIX}_error.log`,
            timestamp: tsFormat,
            level: 'error',
            maxsize: 40000,
            maxFiles: 10,
        }),
        new (winston.transports.File)({
            colorize: true,
            prettyPrint: true,
            name: 'file#combined',
            filename: `${LOG_DIR}/${LOG_PREFIX}/${LOG_PREFIX}_combined.log`,
            timestamp: tsFormat,
            level: process.env.NODE_ENV === 'production' ? 'info' : 'debug',
        }),
    ],
    exceptionHandlers: [
        new (winston.transports.Console)({ 
            colorize: true,
            prettyPrint: true,
            timestamp: tsFormat,
            level: 'info',
            maxsize: 40000,
            maxFiles: 10,
        }),
    ],
});

module.exports = logger;
```

Then just 

```JavaScript
const logger = require('logger');
logger.debug('');
logger.info('');
logger.error('');
```

This also means debug only prints out when in development

**Comment by amercier** [comment]
@vorticalbox Thanks for your message.

However, my use case is not really about the logger implementation itself (whether I use Winston* or my own custom logger). I would like server.js to log its own messages (ex: `Server started on http://localhost:3000/`, middleware warning/errors, etc.) using the logger of my choice. Also, I would like to pass the logger instance to the middlewares context, rather than using a singleton passed through `require`.

**Comment by franciscop** [comment]
That is awesome logging! Feel free to do a PR to include in server those colors, messages, error finding, etc @amercier.

For the current PR, then it's fine and a perfectly valid usecase. However, a couple of small changes:
- Could you do the PR in the branch `plugins`? This is the one more active.
- Could you add some extra validation to make sure it has the correct properties? Either `validate`, [a function that checks](https://github.com/franciscop/server/blob/plugins/utils/options/parse.js#L160) that the value has the expected properties or `options` as an alternative for the children [as seen here](https://github.com/franciscop/server/blob/plugins/utils/options/parse.js#L171):

```js
{
  instance: {
    type: Object,
    options: {
      debug: { required: true, type: 'function' },
      info: { required: true, type: 'function' },
      error: { required: true, type: 'function' },
      ...
    }
  }
}
```

If you cannot do the latter, don't worry, I'll do it. But the PR still has to be in `plugins`.

**Comment by amercier** [comment]
Thanks @franciscop!

I'll do those changes, no worries. I didn't know about `validate`/`options`, is this part of some upcoming plugin API? Sounds great! I'll update this PR as Github now allows changing the destination branch.

I was thinking about publishing my logger as an individual package, similarly to [log](https://www.npmjs.com/package/log). Then I'll submit a PR to use it in server in place of log (it should be super small) :) But it needs testing and a little bit more thinking, so it will come

**Comment by amercier** [comment]
Done.

### Note

I made all the exising logging methods mandatory: `emergency`, `alert`, `critical`, `error`, `warning`, `notice`, `info`, `debug` event though not all of them are used internally right now.

**Pro**: increases future backward-compatibility.
Considering the following scenario:
1. User X uses `server.js` now, implements only `debug`, `info` and `error`. Things for fine.
2. New version of `server.js` is release with a new plugin using `log.warning`. Test pass as `warning` exists in default implementation
3. User X upgrades to latest version, boom, missing `warning` method.

**Con**: users have to implement 8 methods, which can seem overwhelming.

I think pro > con, especially considering `log.instance` can be considered an advanced usage usecase.

@franciscop Let me know if you prefer having only `debug`, `info` and `error` as mandatory methods.

**Comment by franciscop** [comment]
Yeah, it's taking waaay longer than expected because I know once the plugins API is released it basically can never be changed, so any problem now will be carried over.

There should be an `extend` option that is most likely the ideal seeing your latest comments. It will merge the default value with the passed obj (custom logger). But don't worry, I'll implement that part my end, I should have few hours today.

**Comment by amercier** [comment]
Also, I couldn't use the `options` option (I used `validate` instead) because it fails validation when the value is not given at all.

**Pull request closed without merging**
